services:
    metamodels.attribute_langcode.factory:
        class: MetaModels\Attribute\Langcode\AttributeTypeFactory
        arguments:
            - '@database_connection'
            - '@metamodels.table_manipulator'
        tags:
          - { name: metamodels.attribute_factory }
